language: node_js
node_js:
  - "6"

# command to install dependencies
install:
  - npm install
# command to run tests
script:
  - npm run server-start
  - npm run start

deploy:
  provider: heroku
  app: dindin-react
  skip_cleanup: true
  on:
    branch: master